on:
  workflow_dispatch:
  workflow_call:

jobs:
  audit-build:
    name: Audit build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js version 16.x
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn

      # Create audit directory
      - name: Create audit directory
        run: mkdir -p documentation/audit

      # Run audit build
      - name: Audit build
        run: yarn audit:build

      # Cache results
      - name: Cache results
        uses: actions/cache@v3
        with:
          path: documentation/audit
          key: ${{ runner.os }}-audit-build-${{ github.run_id }}

