name: Prod checks

on:
  push:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  prepare-environment:
    needs: [checkout]
    uses: ./.github/workflows/_env.yml

  unit-tests:
    needs: [prepare-environment]
    uses: ./.github/workflows/_unit.build.yml

  e2e-tests:
    needs: [prepare-environment]
    uses: ./.github/workflows/_e2e.build.yml

  build:
    needs: [unit-tests]
    uses: ./.github/workflows/_app.build.yml
    with:
      configuration: prod

  deploy:
    needs: [build]
    uses: ./.github/workflows/_app.deploy.yml
    with:
      configuration: prod
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  build-storybook:
    needs: [prepare-environment]
    uses: ./.github/workflows/_docs.build.yml
    with:
      configuration: prod

  badges:
    needs: [unit-tests, build-storybook]
    uses: ./.github/workflows/_badges.build.yml

  sonar:
    needs: [build, unit-tests]
    uses: ./.github/workflows/_sonar.deploy.yml
    with:
      configuration: prod
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  audit:
    needs: [prepare-environment]
    uses: ./.github/workflows/_audit.build.yml

  docs:
    needs: [build-storybook, unit-tests, audit, badges]
    uses: ./.github/workflows/_docs.deploy.yml
    with:
      configuration: prod
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
